- name: Install webserver with nginx
  hosts: webservers
  become: True
  vars:
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes cache_valid_time=3600
      register: install
    - debug: var=install